name: Docker Image CI - Publish

on:
  release:
    types: [published]

  # Manual run
  workflow_dispatch:

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "$DOCKER_TOKEN" | docker login --username $DOCKER_USERNAME --password-stdin       
    
    - name: Build the Docker image
      run: |
        bash ./build.sh

    - name: Docker Push
      run: |
        docker push -a radstudio/paserver

    - name: Update the Docker Hub description
      uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: radstudio/paserver
